[build]
  publish = "public"
  command = "echo 'Frontend files are already built'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://your-backend-url.herokuapp.com/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/upload-audio"
  to = "https://your-backend-url.herokuapp.com/upload-audio"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://your-backend-url.herokuapp.com/uploads/:splat"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
